#! /usr/bin/env node

/**
 * Script used in tmux to display custom info
 */

const homedir = require('os').homedir(),
	fs = require('fs'),
	path = require('path');

// Define output length
const maxLen = process.argv[2] && Math.floor(process.argv[2] / 4 * 2) || 75,
	rightLen = 25, // ' 11/11/11   1:23:45 pm '.length
	strLen = maxLen - rightLen,
	suffix = '...';

let output = '';

formatOutput(
	currentlyPlaying
	// Add other functions else here to include it in the output
);

output = output || '¯\\_(ツ)_/¯';

process.stdout.write(
	maxLen < 40
		? ''
		: output.length <= strLen
			? output
			: (output.substring(0, strLen - suffix.length) + suffix)
);
process.exit(0);

// Format the any music that is currently, or was recently, playing
function currentlyPlaying() {
	const currentlyPlayingFile = path.resolve(homedir, '.playback.json');
	const isRecent = fs.statSync(currentlyPlayingFile).mtime.getTime() > new Date(Date.now() - (1000 * 60 * 2)).getTime();
	const data = require(currentlyPlayingFile);

	if (isRecent && data && data.song && data.song.artist && data.song.title) {
		const total = _msToMin(data.time.total),
			current = _msToMin(data.time.current);
		const str = `${data.playing ? '▶' : 'Ⅱ'} ${data.song.artist} - ${data.song.title}`;
		const time = `${current}/${total}`;
		return (str.length + time.length + 6 + output.length > strLen
			? str.substr(0, strLen - (time.length + output.length + 7)) + '...'
			: str + ' -')
			+ ' ' + time;
	}
	return '';
}

function formatOutput(...args) {
	args.forEach(func => output = format(func()));

	function format(d) {
		return !d || !output
			? output || d || ''
			: `${output} | ${d}`;
	}
}

function _msToMin(ts) {
	const m = ts / 1000;
	return `${Math.floor(m / 60)}:${String('00' + Math.floor(m % 60)).slice(-2)}`;
}
